### ISSUE TITLE
Download report as PDF link per record

### ISSUE THREAD

**Issue by sidhshar** [geekcoderr/ZAPScan-Flask-Interface#1]
Enable download option for report

![Screenshot from 2023-10-22 08-19-02](https://github.com/geekcoderr/ZAPScan-Flask-Interface/assets/20861064/554da57a-1289-4094-8ae0-f4fb5ce2499f)

**Comment by geekcoderr** [comment]
report download download option is made avilable,as it is default in zap, we have to use external library to convert html to pdf, wil do if yu  say
